name: e2e
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: setup env
        run: |
          cd tools/env
          make up
      - name: install cli
        run: |
          curl https://raw.githubusercontent.com/findy-network/findy-agent-cli/HEAD/install.sh > install.sh
          chmod a+x install.sh
          ./install.sh -b /bin
      - name: install deps
        run: npm ci
      - name: start app
        run: CI=true npm start &
      - name: test
        run: npm run test:e2e
