name: pr-comment

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'dev' }}
    runs-on: ubuntu-latest

    steps:
    - name: Add comment to PR
      run: gh pr comment ${{ github.event.pull_request.number }} --body "PR created by ${{ github.event.pull_request.user.login }}"