name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install deps
        run: npm ci
      - name: build
        run: CI=true npm run build
      - name: lint
        run: npm run test:lint
      - name: test
        run: CI=true npm test
